export const QUESTIONS = [
  "What was your childhood nickname?",
  "In what city did you meet your spouse/significant other?",
  "What is the name of your favorite childhood friend?",
  "What is your oldest sibling’s birthday month and year? (e.g., January 1900)",
  "What is your oldest sibling's middle name?",
  "What school did you attend for sixth grade?",
  "What is your oldest cousin's first and last name?",
  "What was the name of your first stuffed animal?",
  "In what city or town did your mother and father meet?",
  "Where were you when you had your first kiss?",
  "What is the first name of the boy or girl that you first kissed?",
  "What was the last name of your third grade teacher?",
  "In what city does your nearest sibling live?",
  "In what city or town was your first job?",
  "What is the name of a college you applied to but didn't attend?",
];
